# casestudy Negativesample

In [1]:
import pandas as pd
import numpy as np

In [2]:
sdf = pd.read_csv("A_CD.csv",index_col=0)
sdf

MESH:C531617  MESH:C531795  MESH:C535306  MESH:C535323  MESH:C535393  \
C039775             0             0             0             0             0   
C028098             0             0             0             0             0   
C554291             0             0             0             0             0   
C521487             0             0             0             0             0   
C418863             0             0             0             0             0   
...               ...           ...           ...           ...           ...   
C067172             0             0             0             0             0   
C002205             0             0             0             0             0   
C070927             0             0             0             0             0   
C489443             0             0             0             0             0   
C022172             0             0             0             0             0   

         MESH:C535438  MESH:C535469  MESH:C535474  MESH:C535500  MESH:C535506  \
C039775             0             0             0             0             0   
C028098             0             0             0             0             0   
C554291             0             0             0             0             0   
C521487             0             0             0             0             0   
C418863             0             0             0             0             0   
...               ...           ...           ...           ...           ...   
C067172             0             0             0             0             0   
C002205             0             0             0             0             0   
C070927             0             0             0             0             0   
C489443             0             0             0             0             0   
C022172             0             0             0             0             0   

         ...  MESH:D065626  MESH:D065630  MESH:D065631  MESH:D065646  \
C039775  ...             0             0             0             0   
C028098  ...             0             0             0             0   
C554291  ...             0             0             0             0   
C521487  ...             0             0             0             0   
C418863  ...             0             0             0             0   
...      ...           ...           ...           ...           ...   
C067172  ...             0             0             0             0   
C002205  ...             0             0             0             0   
C070927  ...             0             0             0             0   
C489443  ...             0             0             0             0   
C022172  ...             0             0             0             0   

         MESH:D065666  MESH:D065886  MESH:D066087  MESH:D066088  MESH:D066126  \
C039775             0             0             0             0             0   
C028098             0             0             0             0             0   
C554291             0             0             0             0             0   
C521487             0             0             0             0             0   
C418863             0             0             0             0             0   
...               ...           ...           ...           ...           ...   
C067172             0             0             0             0             0   
C002205             0             0             0             0             0   
C070927             0             0             0             0             0   
C489443             0             0             0             0             0   
C022172             0             0             0             0             0   

         MESH:D066253  
C039775             0  
C028098             0  
C554291             0  
C521487             0  
C418863             0  
...               ...  
C067172             0  
C002205             0  
C070927  

In [3]:
drug = sdf.values
drug.shape

(5973, 2447)

In [4]:
x = np.where(drug == 0)
x

(array([   0,    0,    0, ..., 5972, 5972, 5972], dtype=int64),
 array([   0,    1,    2, ..., 2444, 2445, 2446], dtype=int64))

In [5]:
a1 = x[1]+18825
mat1 = a1.T
mat1.shape

(14580797,)

In [6]:
a2 = x[0]
mat2 = a2.T
mat2.shape

(14580797,)

In [7]:
M1 = np.vstack((mat2,mat1))
M1

array([[    0,     0,     0, ...,  5972,  5972,  5972],
       [18825, 18826, 18827, ..., 21269, 21270, 21271]], dtype=int64)

In [8]:
M1.shape

(2, 14580797)

In [9]:
Mat1 = pd.DataFrame(M1.T)
Mat1

0      1
0            0  18825
1            0  18826
2            0  18827
3            0  18828
4            0  18829
...        ...    ...
14580792  5972  21267
14580793  5972  21268
14580794  5972  21269
14580795  5972  21270
14580796  5972  21271

[14580797 rows x 2 columns]

In [10]:
Mat1.to_csv('NegativeSample_casestudy.csv',index=None,header=None)

In [11]:
import random
filename = "NegativeSample_casestudy.csv"                         # Read the file name and remove the  \ and / to the left of the file name.
seeds = [666]
with open(filename, "r", encoding="utf-8") as f:
    lines = f.readlines()
lines = [line.strip(" \n") for line in lines]                    # Remove newlines and Spaces
lines = [line for line in lines if len(line)>0]                  # Remove blank lines
errLines = [line for line in lines if len(line.split(","))!=2]
assert len(errLines)==0, "格式错误：\n" + "\n".join(errLines)    # Check the format, whether each row is two columns

n = len(lines)
for seed in seeds:
    random.seed(0)
    indices = [i for i in range(n)]
    for i in range(n-1, -1, -1):                                 # The Gaunard algorithm creates the scrambled index
        idx = int(random.random() * (i + 1))
        indices[i], indices[idx] = indices[idx], indices[i]
    lines_shuffled = [lines[idx] for idx in indices]
    with open("sf_%d_%s" % (seed, filename), "w", encoding="utf-8") as f:
        f.write("\n".join(lines_shuffled))

In [12]:
df = pd.read_csv("sf_666_NegativeSample_casestudy.csv",header=None)
df.columns = ['left','right']
df

left  right
0         3749  20956
1         4019  19931
2         2019  19632
3         2363  20271
4         2718  20451
...        ...    ...
14580792  3053  19321
14580793  1545  19744
14580794  2511  19597
14580795  4526  20608
14580796  5043  20260

[14580797 rows x 2 columns]

In [13]:
Nega = df.iloc[0:35134]
Nega

left  right
0      3749  20956
1      4019  19931
2      2019  19632
3      2363  20271
4      2718  20451
...     ...    ...
35129  3374  20161
35130  4119  19188
35131  1149  19714
35132  3967  20926
35133  5912  19376

[35134 rows x 2 columns]

In [14]:
Nega.to_csv('NegativeSample.csv',index=None,header=None)